/**
 * Mock `.gitignore` and license templates (mirrors the bgh-repos template
 * endpoints): `GET /gitignore/templates[/{name}]`, `GET /licenses[/{key}]`.
 * Texts are abbreviated; the first line of a license body is its name, which
 * `detectLicense` uses to recognise LICENSE files (the server matches full texts).
 */
import type { Repo } from '../../sync/models';
import { gitFor } from '../git';
import type { MockServer } from '../server';
import { notFound, ok, param } from './util';

const GITIGNORE: Record<string, string> = {
  C: '# Object files\n*.o\n*.ko\n*.obj\n\n# Executables\n*.exe\n*.out\n*.app\n',
  'C++': '# Compiled Object files\n*.o\n*.obj\n\n# Compiled Dynamic libraries\n*.so\n*.dylib\n*.dll\n\n# Executables\n*.exe\n*.out\n',
  Go: '# Binaries for programs and plugins\n*.exe\n*.exe~\n*.dll\n*.so\n*.dylib\n\n# Test binary, built with `go test -c`\n*.test\n\n# Output of the go coverage tool\n*.out\n\n# Go workspace file\ngo.work\n',
  Java: '# Compiled class file\n*.class\n\n# Log file\n*.log\n\n# Package Files\n*.jar\n*.war\n',
  Node: '# Logs\nlogs\n*.log\nnpm-debug.log*\n\n# Dependency directories\nnode_modules/\n\n# dotenv environment variable files\n.env\n',
  Python: '# Byte-compiled / optimized / DLL files\n__pycache__/\n*.py[cod]\n\n# Distribution / packaging\nbuild/\ndist/\n*.egg-info/\n\n# Environments\n.env\n.venv\n',
  Ruby: '*.gem\n/.bundle/\n/coverage/\n/pkg/\n/tmp/\n',
  Rust: '# Generated by Cargo\n/target/\n\n# These are backup files generated by rustfmt\n**/*.rs.bk\n',
  Swift: '# Xcode\nxcuserdata/\n*.xcscmblueprint\n\n# Swift Package Manager\n.build/\n',
};

interface License {
  key: string;
  name: string;
  spdx_id: string;
  description: string;
  featured?: boolean;
}

const LICENSES: License[] = [
  { key: 'agpl-3.0', name: 'GNU Affero General Public License v3.0', spdx_id: 'AGPL-3.0', description: 'Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license.' },
  { key: 'apache-2.0', name: 'Apache License 2.0', spdx_id: 'Apache-2.0', description: 'A permissive license whose main conditions require preservation of copyright and license notices.', featured: true },
  { key: 'bsd-2-clause', name: 'BSD 2-Clause "Simplified" License', spdx_id: 'BSD-2-Clause', description: 'A permissive license that comes in two variants, the BSD 2-Clause and BSD 3-Clause.' },
  { key: 'bsd-3-clause', name: 'BSD 3-Clause "New" or "Revised" License', spdx_id: 'BSD-3-Clause', description: 'A permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the copyright holder or its contributors to promote derived products without written consent.' },
  { key: 'bsl-1.0', name: 'Boost Software License 1.0', spdx_id: 'BSL-1.0', description: 'A simple permissive license only requiring preservation of copyright and license notices for source (and not binary) distribution.' },
  { key: 'cc0-1.0', name: 'Creative Commons Zero v1.0 Universal', spdx_id: 'CC0-1.0', description: 'The Creative Commons CC0 Public Domain Dedication waives copyright interest in a work you’ve created and dedicates it to the world-wide public domain.' },
  { key: 'epl-2.0', name: 'Eclipse Public License 2.0', spdx_id: 'EPL-2.0', description: 'This commercially-friendly copyleft license provides the ability to commercially license binaries.' },
  { key: 'gpl-2.0', name: 'GNU General Public License v2.0', spdx_id: 'GPL-2.0', description: 'The GNU GPL is the most widely used free software license and has a strong copyleft requirement.' },
  { key: 'gpl-3.0', name: 'GNU General Public License v3.0', spdx_id: 'GPL-3.0', description: 'Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications.', featured: true },
  { key: 'lgpl-2.1', name: 'GNU Lesser General Public License v2.1', spdx_id: 'LGPL-2.1', description: 'Primarily used for software libraries, the GNU LGPL requires that derived works be licensed under the same license.' },
  { key: 'mit', name: 'MIT License', spdx_id: 'MIT', description: 'A short and simple permissive license with conditions only requiring preservation of copyright and license notices.', featured: true },
  { key: 'mpl-2.0', name: 'Mozilla Public License 2.0', spdx_id: 'MPL-2.0', description: 'Permissions of this weak copyleft license are conditioned on making available source code of licensed files and modifications of those files under the same license.' },
  { key: 'unlicense', name: 'The Unlicense', spdx_id: 'Unlicense', description: 'A license with no conditions whatsoever which dedicates works to the public domain.' },
];

export const gitignoreTemplate = (name: string): string | undefined => {
  const k = Object.keys(GITIGNORE).find((x) => x.toLowerCase() === name.toLowerCase());
  return k ? GITIGNORE[k] : undefined;
};

const findLicense = (key: string) => LICENSES.find((l) => l.key === key.toLowerCase());
export const isLicenseKey = (key: string): boolean => !!findLicense(key);

const simple = (l: License) => ({ key: l.key, name: l.name, spdx_id: l.spdx_id, url: `/api/v3/licenses/${l.key}`, node_id: btoa(`07:License${l.key}`) });

/** LICENSE file text for a license template ([year] / [fullname] filled in). */
export function licenseText(key: string, owner: string): string | undefined {
  const l = findLicense(key);
  if (!l) return undefined;
  return `${l.name}\n\nCopyright (c) ${new Date().getFullYear()} ${owner}\n\n${l.description}\n`;
}

/** `license` field of a repository for its LICENSE file content (null without one). */
export function detectLicense(text: string | undefined): Record<string, unknown> | null {
  if (text === undefined) return null;
  const first = text.trimStart().split('\n')[0]?.trim().toLowerCase() ?? '';
  const l = LICENSES.find((x) => x.name.toLowerCase() === first);
  return l ? simple(l) : { key: 'other', name: 'Other', spdx_id: 'NOASSERTION', url: null, node_id: btoa('07:Licenseother') };
}

/** `license` of a repository, from the LICENSE file on its default branch. */
export function repoLicense(server: MockServer, repo: Repo): Record<string, unknown> | null {
  const git = gitFor(server, repo);
  const tip = git.resolve(repo.defaultBranch);
  return detectLicense(tip ? git.commit(tip).files.get('LICENSE') : undefined);
}

export function installLicenseMocks(server: MockServer): void {
  const R = (method: string, pattern: string, handler: Parameters<MockServer['route']>[2]) => server.route(method, pattern, handler, { public: true });
  R('GET', '/api/v3/gitignore/templates', () => ok(Object.keys(GITIGNORE).sort()));
  R('GET', '/api/v3/gitignore/templates/:name', (ctx) => {
    const name = Object.keys(GITIGNORE).find((x) => x.toLowerCase() === param(ctx, 1).toLowerCase());
    return name ? ok({ name, source: GITIGNORE[name] }) : notFound();
  });
  R('GET', '/api/v3/licenses', (ctx) => {
    const per = Math.min(100, Math.max(1, Number(ctx.url.searchParams.get('per_page') ?? 30)));
    const p = Math.max(1, Number(ctx.url.searchParams.get('page') ?? 1));
    return ok(LICENSES.slice((p - 1) * per, p * per).map(simple));
  });
  R('GET', '/api/v3/licenses/:key', (ctx) => {
    const l = findLicense(param(ctx, 1));
    if (!l) return notFound();
    return ok({
      ...simple(l),
      html_url: `https://choosealicense.com/licenses/${l.key}/`,
      description: l.description,
      implementation: 'Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.',
      permissions: ['commercial-use', 'modifications', 'distribution', 'private-use'],
      conditions: l.key === 'unlicense' || l.key === 'cc0-1.0' ? [] : ['include-copyright'],
      limitations: ['liability', 'warranty'],
      body: licenseText(l.key, '[fullname]')!.replace(String(new Date().getFullYear()), '[year]'),
      featured: !!l.featured,
    });
  });
}
