//! `strategy.matrix` expansion, following GitHub's documented algorithm.

use serde_json::{Map, Value};

use super::WorkflowError;

/// GitHub's limit on jobs generated by one matrix.
pub const MAX_MATRIX_COMBINATIONS: usize = 256;

/// Expands an already-evaluated matrix object into its job combinations.
///
/// 1. Cartesian product of all keys other than `include` / `exclude`, in key
///    order (the first key varies slowest).
/// 2. `exclude` entries remove every combination that matches all of the
///    entry's key/value pairs (partial matches allowed; JSON equality).
/// 3. Each `include` entry is merged into every *original* combination whose
///    original matrix values it would not overwrite (values added by earlier
///    includes may be overwritten). If it fits no original combination it is
///    appended as a new combination.
///
/// Errors when the matrix is not an object, a vector is not a non-empty
/// array, `include`/`exclude` are not arrays of objects, the matrix defines
/// nothing at all, or more than [`MAX_MATRIX_COMBINATIONS`] result.
pub fn expand_matrix(matrix: &Value) -> Result<Vec<Map<String, Value>>, WorkflowError> {
    let obj = matrix
        .as_object()
        .ok_or_else(|| WorkflowError::invalid("matrix must be an object"))?;

    let mut vectors: Vec<(&String, &Vec<Value>)> = Vec::new();
    let mut include: &[Value] = &[];
    let mut exclude: &[Value] = &[];
    for (key, value) in obj {
        match key.as_str() {
            "include" | "exclude" => {
                let arr = value.as_array().ok_or_else(|| {
                    WorkflowError::invalid(format!("matrix '{key}' must be an array"))
                })?;
                if let Some(bad) = arr.iter().position(|v| !v.is_object()) {
                    return Err(WorkflowError::invalid(format!(
                        "matrix '{key}' entry {} must be an object",
                        bad + 1
                    )));
                }
                if key == "include" {
                    include = arr;
                } else {
                    exclude = arr;
                }
            }
            _ => {
                let arr = value.as_array().ok_or_else(|| {
                    WorkflowError::invalid(format!("matrix vector '{key}' must be an array"))
                })?;
                if arr.is_empty() {
                    return Err(WorkflowError::invalid(format!(
                        "matrix vector '{key}' does not contain any values"
                    )));
                }
                vectors.push((key, arr));
            }
        }
    }
    if vectors.is_empty() && include.is_empty() {
        return Err(WorkflowError::invalid(
            "matrix must define at least one vector or include entry",
        ));
    }

    let too_many = || {
        WorkflowError::invalid(format!(
            "matrix generates more than {MAX_MATRIX_COMBINATIONS} combinations"
        ))
    };

    // 1. Cartesian product. Guard the size before materialising it; excludes
    //    can shrink it, so allow a generous intermediate size.
    let product_size = vectors
        .iter()
        .try_fold(1usize, |acc, (_, arr)| acc.checked_mul(arr.len()))
        .ok_or_else(too_many)?;
    if product_size > MAX_MATRIX_COMBINATIONS * 64 {
        return Err(too_many());
    }
    let mut combos: Vec<Map<String, Value>> = if vectors.is_empty() {
        Vec::new()
    } else {
        let mut acc = vec![Map::new()];
        for (key, values) in &vectors {
            let mut next = Vec::with_capacity(acc.len() * values.len());
            for combo in &acc {
                for v in values.iter() {
                    let mut c = combo.clone();
                    c.insert((*key).clone(), v.clone());
                    next.push(c);
                }
            }
            acc = next;
        }
        acc
    };

    // 2. Exclude.
    combos.retain(|combo| {
        !exclude.iter().filter_map(Value::as_object).any(|ex| {
            ex.iter()
                .all(|(k, v)| combo.get(k).is_some_and(|cv| json_partial_eq(v, cv)))
        })
    });

    // 3. Include.
    let original_count = combos.len();
    let is_original_key = |k: &str| vectors.iter().any(|(key, _)| key.as_str() == k);
    let mut appended: Vec<Map<String, Value>> = Vec::new();
    for inc in include.iter().filter_map(Value::as_object) {
        let mut added = false;
        for combo in combos.iter_mut().take(original_count) {
            let compatible = inc
                .iter()
                .all(|(k, v)| !is_original_key(k) || combo.get(k) == Some(v));
            if compatible {
                for (k, v) in inc {
                    combo.insert(k.clone(), v.clone());
                }
                added = true;
            }
        }
        if !added {
            appended.push(inc.clone());
        }
    }
    combos.extend(appended);

    if combos.len() > MAX_MATRIX_COMBINATIONS {
        return Err(too_many());
    }
    Ok(combos)
}

/// Exclude matching: an object in an exclude entry matches when all of its
/// keys match (recursively); everything else uses JSON equality.
fn json_partial_eq(pattern: &Value, value: &Value) -> bool {
    match (pattern, value) {
        (Value::Object(p), Value::Object(v)) => p
            .iter()
            .all(|(k, pv)| v.get(k).is_some_and(|vv| json_partial_eq(pv, vv))),
        _ => pattern == value,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn expand(v: Value) -> Vec<Value> {
        expand_matrix(&v)
            .unwrap()
            .into_iter()
            .map(Value::Object)
            .collect()
    }

    #[test]
    fn simple_product_in_key_order() {
        let r = expand(json!({"version": [10, 12, 14], "os": ["ubuntu-latest", "windows-latest"]}));
        assert_eq!(r.len(), 6);
        assert_eq!(r[0], json!({"version": 10, "os": "ubuntu-latest"}));
        assert_eq!(r[1], json!({"version": 10, "os": "windows-latest"}));
        assert_eq!(r[5], json!({"version": 14, "os": "windows-latest"}));
        // key order preserved within each combination
        let keys: Vec<_> = r[0].as_object().unwrap().keys().cloned().collect();
        assert_eq!(keys, ["version", "os"]);
    }

    #[test]
    fn docs_fruit_animal_example() {
        let r = expand(json!({
            "fruit": ["apple", "pear"],
            "animal": ["cat", "dog"],
            "include": [
                {"color": "green"},
                {"color": "pink", "animal": "cat"},
                {"fruit": "apple", "shape": "circle"},
                {"fruit": "banana"},
                {"fruit": "banana", "animal": "cat"}
            ]
        }));
        assert_eq!(
            r,
            vec![
                json!({"fruit": "apple", "animal": "cat", "color": "pink", "shape": "circle"}),
                json!({"fruit": "apple", "animal": "dog", "color": "green", "shape": "circle"}),
                json!({"fruit": "pear", "animal": "cat", "color": "pink"}),
                json!({"fruit": "pear", "animal": "dog", "color": "green"}),
                json!({"fruit": "banana"}),
                json!({"fruit": "banana", "animal": "cat"}),
            ]
        );
    }

    #[test]
    fn docs_os_node_include_adds_npm() {
        let r = expand(json!({
            "os": ["windows-latest", "ubuntu-latest"],
            "node": [14, 16],
            "include": [{"os": "windows-latest", "node": 16, "npm": 6}]
        }));
        assert_eq!(r.len(), 4);
        assert_eq!(r[1], json!({"os": "windows-latest", "node": 16, "npm": 6}));
        assert_eq!(r[0], json!({"os": "windows-latest", "node": 14}));
        assert!(r[2].get("npm").is_none());
    }

    #[test]
    fn docs_include_extends_with_new_combination() {
        let r = expand(json!({
            "os": ["windows-latest", "ubuntu-latest"],
            "node": [14, 16],
            "include": [
                {"os": "windows-latest", "node": 17}
            ]
        }));
        assert_eq!(r.len(), 5);
        assert_eq!(r[4], json!({"os": "windows-latest", "node": 17}));
    }

    #[test]
    fn docs_include_only() {
        let r = expand(json!({
            "include": [
                {"site": "production", "datacenter": "site-a"},
                {"site": "staging", "datacenter": "site-b"}
            ]
        }));
        assert_eq!(
            r,
            vec![
                json!({"site": "production", "datacenter": "site-a"}),
                json!({"site": "staging", "datacenter": "site-b"}),
            ]
        );
    }

    #[test]
    fn docs_exclude_example() {
        let r = expand(json!({
            "os": ["macos-latest", "windows-latest"],
            "version": [12, 14, 16],
            "environment": ["staging", "production"],
            "exclude": [
                {"os": "macos-latest", "version": 12, "environment": "production"},
                {"os": "windows-latest", "version": 16}
            ]
        }));
        assert_eq!(r.len(), 9);
        assert!(
            !r.contains(&json!({"os": "macos-latest", "version": 12, "environment": "production"}))
        );
        assert!(
            r.contains(&json!({"os": "macos-latest", "version": 12, "environment": "staging"}))
        );
        assert!(
            !r.iter()
                .any(|c| c["os"] == "windows-latest" && c["version"] == 16)
        );
    }

    #[test]
    fn include_can_overwrite_added_values_but_not_original() {
        let r = expand(json!({
            "os": ["linux", "mac"],
            "include": [
                {"arch": "x64"},
                {"os": "mac", "arch": "arm64"}
            ]
        }));
        assert_eq!(
            r,
            vec![
                json!({"os": "linux", "arch": "x64"}),
                json!({"os": "mac", "arch": "arm64"}),
            ]
        );
    }

    #[test]
    fn include_after_exclude_targets_remaining() {
        let r = expand(json!({
            "os": ["linux", "mac"],
            "exclude": [{"os": "mac"}],
            "include": [{"os": "mac", "experimental": true}]
        }));
        assert_eq!(
            r,
            vec![
                json!({"os": "linux"}),
                json!({"os": "mac", "experimental": true})
            ]
        );
    }

    #[test]
    fn object_values_and_partial_exclude() {
        let r = expand(json!({
            "target": [{"os": "linux", "arch": "x64"}, {"os": "mac", "arch": "arm64"}],
            "exclude": [{"target": {"os": "mac"}}]
        }));
        assert_eq!(r, vec![json!({"target": {"os": "linux", "arch": "x64"}})]);
    }

    #[test]
    fn exclude_everything_yields_empty() {
        let r = expand(json!({"os": ["a"], "exclude": [{"os": "a"}]}));
        assert!(r.is_empty());
    }

    #[test]
    fn errors() {
        assert!(expand_matrix(&json!("x")).is_err());
        assert!(expand_matrix(&json!({})).is_err());
        assert!(expand_matrix(&json!({"os": "linux"})).is_err());
        assert!(expand_matrix(&json!({"os": []})).is_err());
        assert!(expand_matrix(&json!({"os": ["a"], "include": {"x": 1}})).is_err());
        assert!(expand_matrix(&json!({"os": ["a"], "exclude": ["x"]})).is_err());
    }

    #[test]
    fn limit_256() {
        let sixteen: Vec<u32> = (0..16).collect();
        assert_eq!(
            expand_matrix(&json!({"a": sixteen, "b": sixteen}))
                .unwrap()
                .len(),
            256
        );
        let err = expand_matrix(&json!({"a": sixteen, "b": sixteen, "include": [{"a": 99}]}))
            .unwrap_err();
        assert!(err.to_string().contains("256"));
        let big: Vec<u32> = (0..1000).collect();
        assert!(expand_matrix(&json!({"a": big, "b": big, "c": big})).is_err());
        // excludes may bring a product back under the limit
        let r = expand_matrix(
            &json!({"a": (0..17).collect::<Vec<_>>(), "b": sixteen, "exclude": [{"a": 16}]}),
        )
        .unwrap();
        assert_eq!(r.len(), 256);
    }
}
