#!/usr/bin/env bash
# Dev loop: backend (auto-rebuild with cargo-watch when installed) + Vite dev
# server, together; Ctrl-C stops both.
#
#   ./scripts/dev.sh                 backend on :3000, web on :5173 (proxying to :3000)
#   ./scripts/dev.sh --no-web        backend only
#   ./scripts/dev.sh --no-backend    web only (BGH_BACKEND decides where it proxies)
#   ./scripts/dev.sh --mock          web only, in-browser mock backend
#   ./scripts/dev.sh --setup         run scripts/dev-setup.sh (postgres + redis) first
#
# Environment: DATABASE_URL, REDIS_URL and every BGH_* variable are passed
# through (defaults: local postgres/redis from dev-setup.sh). BGH_PORT
# (default 3000) and WEB_PORT (default 5173) pick the ports.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

run_backend=1
run_web=1
mock=0
setup=0
for arg in "$@"; do
  case "$arg" in
    --no-web) run_web=0 ;;
    --no-backend) run_backend=0 ;;
    --mock) mock=1; run_backend=0 ;;
    --setup) setup=1 ;;
    -h|--help) awk 'NR==1{next} !/^#/{exit} {sub(/^# ?/,""); print}' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

export DATABASE_URL="${DATABASE_URL:-postgres://postgres:postgres@localhost/bgh}"
export REDIS_URL="${REDIS_URL:-redis://127.0.0.1/}"
BGH_PORT="${BGH_PORT:-3000}"
WEB_PORT="${WEB_PORT:-5173}"
export BGH_LISTEN="${BGH_LISTEN:-127.0.0.1:$BGH_PORT}"
# Links generated by the API should point at the Vite server the browser uses.
if [[ $run_web == 1 ]]; then
  export BGH_BASE_URL="${BGH_BASE_URL:-http://localhost:$WEB_PORT}"
else
  export BGH_BASE_URL="${BGH_BASE_URL:-http://localhost:$BGH_PORT}"
fi
export BGH_BACKEND="${BGH_BACKEND:-http://127.0.0.1:$BGH_PORT}"
export RUST_LOG="${RUST_LOG:-info,sqlx=warn,tower_http=info}"

if [[ $setup == 1 ]]; then
  "$ROOT/scripts/dev-setup.sh"
fi

pids=()
cleanup() {
  trap - INT TERM EXIT
  for pid in "${pids[@]}"; do
    # Kill the whole process group of each child (cargo-watch -> cargo -> bgh).
    kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
  done
  wait 2>/dev/null || true
}
trap cleanup INT TERM EXIT

# Prefix each line of a child's output with a (colored) tag.
prefix() {
  local tag="$1" color="$2" line
  [[ -t 1 ]] && tag=$'\e['"${color}m${tag}"$'\e[0m'
  while IFS= read -r line || [[ -n $line ]]; do
    printf '%s %s\n' "$tag" "$line"
  done
}

# `set -m` runs each background job in its own process group, so cleanup can
# stop the whole tree.
set -m

if [[ $run_backend == 1 ]]; then
  if cargo watch --version >/dev/null 2>&1; then
    backend=(cargo watch --quiet --clear=false
      -w crates -w migrations -w Cargo.toml -w Cargo.lock
      -x "run -p bgh-server --bin bgh -- serve")
  else
    echo "[dev] cargo-watch not found (cargo install cargo-watch); running without auto-reload" >&2
    backend=(cargo run -p bgh-server --bin bgh -- serve)
  fi
  ( "${backend[@]}" 2>&1 | prefix "[api]" "36" ) &
  pids+=($!)
fi

if [[ $run_web == 1 ]]; then
  if [[ ! -d web/node_modules ]]; then
    echo "[dev] installing web dependencies (npm ci)" >&2
    (cd web && npm ci --no-audit --no-fund)
  fi
  web_script=dev
  [[ $mock == 1 ]] && web_script=dev:mock
  ( cd web && npm run "$web_script" -- --port "$WEB_PORT" --strictPort 2>&1 | prefix "[web]" "35" ) &
  pids+=($!)
fi

set +m

if [[ ${#pids[@]} == 0 ]]; then
  echo "nothing to run" >&2
  exit 2
fi

msg="[dev]"
[[ $run_backend == 1 ]] && msg+=" backend: $BGH_BACKEND"
[[ $run_web == 1 ]] && msg+=" web: http://localhost:$WEB_PORT"
echo "$msg  (Ctrl-C to stop)" >&2
# Exit (and stop the other side) as soon as either child exits.
wait -n || true   # bash >= 4.3
