[package]
name = "bgh-notify"
description = "Notifications, subscriptions, webhooks, email"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bgh-core.workspace = true
bgh-git.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
anyhow.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
chrono.workspace = true
uuid.workspace = true
rand.workspace = true
base64.workspace = true
sha2.workspace = true
hex.workspace = true
http.workspace = true
bytes.workspace = true
reqwest.workspace = true
lettre.workspace = true
hmac.workspace = true
sha1.workspace = true
url.workspace = true

[dev-dependencies]
bgh-core = { workspace = true, features = ["testing"] }
bgh-server = { workspace = true, features = ["testing"] }
tokio.workspace = true
